Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - lib/**/*
    - spec/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

Naming/MemoizedInstanceVariableName:
 EnforcedStyleForLeadingUnderscores: optional

Metrics/LineLength:
 # Ignore class definitions and comments
 IgnoredPatterns: ['^class .*','^\s*\# .*']
